version: '3.8'

services:
  avito-scanner:
    build: .
    container_name: avito-scanner-pro
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - /dev/shm:/dev/shm
    env_file:
      - .env
    restart: unless-stopped